email: kaylon.contact@gmail.com
description: Personal Page
baseurl: ""
url: "https://kaaylooon.github.io"
remote_theme: []

markdown: kramdown
highlighter: rouge

collections:
  projetos:
    output: true
    permalink: /projetos/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
