title: Kaylon Souza
email: kaylon.contact@gmail.com
description: Personal Page
author: Kaylon Souza
github_username: kaaylooon
linkedin_username: kaylonsouza
baseurl: ""
url: "https://kaaylooon.github.io"
remote_theme: []

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

collections:
  projetos:
    output: true
    permalink: /projetos/:path/

defaults:
  - scope:
      path: "_projetos"
    values:
      layout: projeto
      og_type: article

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
